MtPyre_Exterior_Dave_House_MapScripts::
	.byte 0


MtPyre_Exterior_Dave_House_EventScript_Gengar::
# 5 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	lock
# 6 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	applymovement 3, Common_Movement_FacePlayer
# 7 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	waitmovement 3
# 8 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	playmoncry SPECIES_GENGAR, CRY_MODE_ENCOUNTER
# 9 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	delay 20
# 10 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	release
	end


MtPyre_Exterior_Dave_House_EventScript_Mimikyu::
# 15 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	lock
# 16 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	applymovement 4, Common_Movement_FacePlayer
# 17 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	waitmovement 4
# 18 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	playmoncry SPECIES_MIMIKYU, CRY_MODE_ENCOUNTER
# 19 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	delay 20
# 20 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	release
	end


MtPyre_Exterior_Dave_House_EventScript_Banette::
# 25 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	lock
# 26 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	applymovement 2, Common_Movement_FacePlayer
# 27 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	waitmovement 2
# 28 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	playmoncry SPECIES_BANETTE, CRY_MODE_ENCOUNTER
# 29 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	delay 20
# 30 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	release
	end


MtPyre_Exterior_Dave_House_EventScript_Litwick::
# 35 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	lock
# 36 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	applymovement 2, Common_Movement_FacePlayer
# 37 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	waitmovement 2
# 38 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	playmoncry SPECIES_LITWICK, CRY_MODE_ENCOUNTER
# 39 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	delay 20
# 40 "data/maps/MtPyre_Exterior_Dave_House/scripts.pory"
	release
	end

