SnowdriftCity_House2_MapScripts::
	.byte 0


SnowdriftCity_House2_EventScript_LittleNerd::
# 4 "data/maps/SnowdriftCity_House2/scripts.pory"
	msgbox SnowdriftCity_House2_EventScript_LittleNerd_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House2_EventScript_HexManiac::
# 10 "data/maps/SnowdriftCity_House2/scripts.pory"
	msgbox SnowdriftCity_House2_EventScript_HexManiac_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House2_EventScript_Maniac::
# 18 "data/maps/SnowdriftCity_House2/scripts.pory"
	msgbox SnowdriftCity_House2_EventScript_Maniac_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House2_EventScript_LittleNerd_Text_0:
# 4 "data/maps/SnowdriftCity_House2/scripts.pory"
	.string "Indubitably resplendent!\n Riveting, indeed!$"

SnowdriftCity_House2_EventScript_HexManiac_Text_0:
# 10 "data/maps/SnowdriftCity_House2/scripts.pory"
	.string "Before living here, we lived in\n LILYCOVE.\p We first met at MT. PYRE.\n It was love at first sight.$"

SnowdriftCity_House2_EventScript_Maniac_Text_0:
# 18 "data/maps/SnowdriftCity_House2/scripts.pory"
	.string "Even though I look like this,\n I'm really a family man.$"
