SnowdriftCity_House2_MapScripts::
	.byte 0


SnowdriftCity_House2_EventScript_LittleNerd::
# 4 "data/maps/SnowdriftCity_House2/scripts.pory"
	msgbox SnowdriftCity_House2_EventScript_LittleNerd_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House2_EventScript_HexManiac::
# 9 "data/maps/SnowdriftCity_House2/scripts.pory"
	msgbox SnowdriftCity_House2_EventScript_HexManiac_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House2_EventScript_Maniac::
# 15 "data/maps/SnowdriftCity_House2/scripts.pory"
	msgbox SnowdriftCity_House2_EventScript_Maniac_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House2_EventScript_LittleNerd_Text_0:
# 4 "data/maps/SnowdriftCity_House2/scripts.pory"
	.string "Indubitably resplendent!$"

SnowdriftCity_House2_EventScript_HexManiac_Text_0:
# 9 "data/maps/SnowdriftCity_House2/scripts.pory"
	.string "We moved here from LILYCOVE.\n We met at MT. PYRE.$"

SnowdriftCity_House2_EventScript_Maniac_Text_0:
# 15 "data/maps/SnowdriftCity_House2/scripts.pory"
	.string "Even though I look like this,\n I'm a family man.$"
