SnowdriftCity_House3_MapScripts::
	.byte 0


SnowdriftCity_House3_EventScript_Man::
# 4 "data/maps/SnowdriftCity_House3/scripts.pory"
	msgbox SnowdriftCity_House3_EventScript_Man_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House3_EventScript_Woman::
# 11 "data/maps/SnowdriftCity_House3/scripts.pory"
	msgbox SnowdriftCity_House3_EventScript_Woman_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House3_EventScript_Man_Text_0:
# 4 "data/maps/SnowdriftCity_House3/scripts.pory"
	.string "We've lived here all our lives.\p We do occasionally go down the\n mountain though.$"

SnowdriftCity_House3_EventScript_Woman_Text_0:
# 11 "data/maps/SnowdriftCity_House3/scripts.pory"
	.string "There's a legend that a POKéMON\n living deep in the mountain is\l the source of the geothermal energy.$"
