RatCave_B2F_MapScripts::
	.byte 0


Petalburg_RatCave_Rock::
# 4 "data/maps/RatCave_B2F/scripts.pory"
	lock
# 5 "data/maps/RatCave_B2F/scripts.pory"
	msgbox Petalburg_RatCave_Rock_Text_0
# 7 "data/maps/RatCave_B2F/scripts.pory"
	waitmessage
# 8 "data/maps/RatCave_B2F/scripts.pory"
	release
	return


Petalburg_RatCave_Rock_Text_0:
# 5 "data/maps/RatCave_B2F/scripts.pory"
	.string "Doesn't look like the cave in \n can be cleared anytime soon.$"
