# 1 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_MapScripts::
# 2 "data/maps/VictoryRoad_B2F/scripts.pory"
	.byte 0
# 3 "data/maps/VictoryRoad_B2F/scripts.pory"

# 4 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Vito::
# 5 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_VITO, VictoryRoad_B2F_Text_VitoIntro, VictoryRoad_B2F_Text_VitoDefeat
# 6 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_VitoPostBattle, MSGBOX_AUTOCLOSE
# 7 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 8 "data/maps/VictoryRoad_B2F/scripts.pory"

# 9 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Owen::
# 10 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_OWEN, VictoryRoad_B2F_Text_OwenIntro, VictoryRoad_B2F_Text_OwenDefeat
# 11 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_OwenPostBattle, MSGBOX_AUTOCLOSE
# 12 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 13 "data/maps/VictoryRoad_B2F/scripts.pory"

# 14 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Caroline::
# 15 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_CAROLINE, VictoryRoad_B2F_Text_CarolineIntro, VictoryRoad_B2F_Text_CarolineDefeat
# 16 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_CarolinePostBattle, MSGBOX_AUTOCLOSE
# 17 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 18 "data/maps/VictoryRoad_B2F/scripts.pory"

# 19 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Julie::
# 20 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_JULIE, VictoryRoad_B2F_Text_JulieIntro, VictoryRoad_B2F_Text_JulieDefeat
# 21 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_JuliePostBattle, MSGBOX_AUTOCLOSE
# 22 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 23 "data/maps/VictoryRoad_B2F/scripts.pory"

# 24 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Felix::
# 25 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_FELIX, VictoryRoad_B2F_Text_FelixIntro, VictoryRoad_B2F_Text_FelixDefeat
# 26 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_FelixPostBattle, MSGBOX_AUTOCLOSE
# 27 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 28 "data/maps/VictoryRoad_B2F/scripts.pory"

# 29 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Dianne::
# 30 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_DIANNE, VictoryRoad_B2F_Text_DianneIntro, VictoryRoad_B2F_Text_DianneDefeat
# 31 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_DiannePostBattle, MSGBOX_AUTOCLOSE
# 32 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 33 "data/maps/VictoryRoad_B2F/scripts.pory"

# 34 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoIntro:
# 35 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I trained together with my whole family,\n"
# 36 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "every one of us!\l"
# 37 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'm not losing to anyone!$"
# 38 "data/maps/VictoryRoad_B2F/scripts.pory"

# 39 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoDefeat:
# 40 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Better than my family?!\n"
# 41 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Is that possible?!$"
# 42 "data/maps/VictoryRoad_B2F/scripts.pory"

# 43 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoPostBattle:
# 44 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I was better than everyone in my\n"
# 45 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "family. I've never lost before…\p"
# 46 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've lost my confidence…\n"
# 47 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Maybe I'll go home…$"
# 48 "data/maps/VictoryRoad_B2F/scripts.pory"

# 49 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenIntro:
# 50 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'd heard that there was a tough\n"
# 51 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "little kid around. Do they mean you?$"
# 52 "data/maps/VictoryRoad_B2F/scripts.pory"

# 53 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenDefeat:
# 54 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The little shrimp is tough!$"
# 55 "data/maps/VictoryRoad_B2F/scripts.pory"

# 56 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenPostBattle:
# 57 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The rumors I heard, that tough little\n"
# 58 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "kid is from PETALBURG CITY.$"
# 59 "data/maps/VictoryRoad_B2F/scripts.pory"

# 60 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolineIntro:
# 61 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You must be getting a little tired.$"
# 62 "data/maps/VictoryRoad_B2F/scripts.pory"

# 63 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolineDefeat:
# 64 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "No signs of tiring at all!$"
# 65 "data/maps/VictoryRoad_B2F/scripts.pory"

# 66 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolinePostBattle:
# 67 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "VICTORY ROAD and the POKéMON LEAGUE\n"
# 68 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "are long and grueling challenges.\l"
# 69 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Beware of fatigue!$"
# 70 "data/maps/VictoryRoad_B2F/scripts.pory"

# 71 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JulieIntro:
# 72 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You shouldn't get complacent just\n"
# 73 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "because you have a lot of GYM BADGES.\p"
# 74 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "There's always going to be someone\n"
# 75 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "who's better than you!$"
# 76 "data/maps/VictoryRoad_B2F/scripts.pory"

# 77 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JulieDefeat:
# 78 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You're better than me!$"
# 79 "data/maps/VictoryRoad_B2F/scripts.pory"

# 80 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JuliePostBattle:
# 81 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Gaze on your collected BADGES and\n"
# 82 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "remember the TRAINERS you've faced.$"
# 83 "data/maps/VictoryRoad_B2F/scripts.pory"

# 84 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixIntro:
# 85 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've come this far, but the tension's\n"
# 86 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "giving me awful stomach pain…$"
# 87 "data/maps/VictoryRoad_B2F/scripts.pory"

# 88 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixDefeat:
# 89 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Ooh…\n"
# 90 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "It hurts…$"
# 91 "data/maps/VictoryRoad_B2F/scripts.pory"

# 92 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixPostBattle:
# 93 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I can't help getting all tense knowing\n"
# 94 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "that I'm nearing the POKéMON LEAGUE.\p"
# 95 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "It's all I can do to feign calm.$"
# 96 "data/maps/VictoryRoad_B2F/scripts.pory"

# 97 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DianneIntro:
# 98 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The elite among the elite gather in\n"
# 99 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "this cave.\p"
# 100 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "How are you finding it?$"
# 101 "data/maps/VictoryRoad_B2F/scripts.pory"

# 102 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DianneDefeat:
# 103 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Not rattled in the least bit!$"
# 104 "data/maps/VictoryRoad_B2F/scripts.pory"

# 105 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DiannePostBattle:
# 106 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You do have guts! I like that!\n"
# 107 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Keep it going!$"

VictoryRoad_B2F_EventScript_Kommo_o::
# 112 "data/maps/VictoryRoad_B2F/scripts.pory"
	lockall
# 113 "data/maps/VictoryRoad_B2F/scripts.pory"
	setflag FLAG_KOMMO_O_TOTEM
# 114 "data/maps/VictoryRoad_B2F/scripts.pory"
	applymovement 8, Common_Movement_FacePlayer
# 115 "data/maps/VictoryRoad_B2F/scripts.pory"
	waitmovement 8
# 116 "data/maps/VictoryRoad_B2F/scripts.pory"
	playmoncry SPECIES_KOMMO_O, CRY_MODE_ENCOUNTER
# 117 "data/maps/VictoryRoad_B2F/scripts.pory"
	delay 40
# 118 "data/maps/VictoryRoad_B2F/scripts.pory"
	waitmoncry
# 119 "data/maps/VictoryRoad_B2F/scripts.pory"
	setwildbattle SPECIES_KOMMO_O_TOTEM, 49, ITEM_DRAGON_SCALE
# 120 "data/maps/VictoryRoad_B2F/scripts.pory"
	dowildbattle
# 121 "data/maps/VictoryRoad_B2F/scripts.pory"
	specialvar VAR_RESULT, GetBattleOutcome
# 122 "data/maps/VictoryRoad_B2F/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_CAUGHT
	goto_if_eq VictoryRoad_B2F_EventScript_Kommo_o_2
# 125 "data/maps/VictoryRoad_B2F/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_WON
	goto_if_eq VictoryRoad_B2F_EventScript_Kommo_o_3
# 128 "data/maps/VictoryRoad_B2F/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_RAN
	goto_if_eq VictoryRoad_B2F_EventScript_Kommo_o_4
# 131 "data/maps/VictoryRoad_B2F/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED
	goto_if_eq VictoryRoad_B2F_EventScript_Kommo_o_5
VictoryRoad_B2F_EventScript_Kommo_o_1:
# 134 "data/maps/VictoryRoad_B2F/scripts.pory"
	waitmessage
# 135 "data/maps/VictoryRoad_B2F/scripts.pory"
	releaseall
	end

VictoryRoad_B2F_EventScript_Kommo_o_2:
# 123 "data/maps/VictoryRoad_B2F/scripts.pory"
	call KommoOWon_Caught
	goto VictoryRoad_B2F_EventScript_Kommo_o_1

VictoryRoad_B2F_EventScript_Kommo_o_3:
# 126 "data/maps/VictoryRoad_B2F/scripts.pory"
	call KommoOWon_Caught
	goto VictoryRoad_B2F_EventScript_Kommo_o_1

VictoryRoad_B2F_EventScript_Kommo_o_4:
# 129 "data/maps/VictoryRoad_B2F/scripts.pory"
	call KommoOFailed
	goto VictoryRoad_B2F_EventScript_Kommo_o_1

VictoryRoad_B2F_EventScript_Kommo_o_5:
# 132 "data/maps/VictoryRoad_B2F/scripts.pory"
	call KommoOFailed
	goto VictoryRoad_B2F_EventScript_Kommo_o_1


KommoOWon_Caught::
# 140 "data/maps/VictoryRoad_B2F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 141 "data/maps/VictoryRoad_B2F/scripts.pory"
	removeobject 8
# 142 "data/maps/VictoryRoad_B2F/scripts.pory"
	fadescreenspeed FADE_FROM_BLACK, 5
	return


KommoOFailed::
# 147 "data/maps/VictoryRoad_B2F/scripts.pory"
	playmoncry SPECIES_KOMMO_O, CRY_MODE_ENCOUNTER
# 148 "data/maps/VictoryRoad_B2F/scripts.pory"
	delay 20
# 149 "data/maps/VictoryRoad_B2F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 150 "data/maps/VictoryRoad_B2F/scripts.pory"
	removeobject 8
# 151 "data/maps/VictoryRoad_B2F/scripts.pory"
	fadescreenspeed FADE_FROM_BLACK, 5
# 152 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox KommoOFailed_Text_0
	return


KommoOFailed_Text_0:
# 152 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The KOMMO-O disappeared…$"
