Route135_House2_MapScripts::
	.byte 0


Route135_House2_Man::
# 4 "data/maps/Route135_House2/scripts.pory"
	msgbox Route135_House2_Man_Text_0, MSGBOX_NPC
	end


Route135_House2_Woman::
# 12 "data/maps/Route135_House2/scripts.pory"
	msgbox Route135_House2_Woman_Text_0, MSGBOX_NPC
	end


Route135_House2_Man_Text_0:
# 4 "data/maps/Route135_House2/scripts.pory"
	.string "A lot more people have been stopping\n by here recently.\p Did they finally make it easier to get\n all the way out here?$"

Route135_House2_Woman_Text_0:
# 12 "data/maps/Route135_House2/scripts.pory"
	.string "We've lived here all our lives.\p It really feels so far away from\n the rest of the region.$"
