SnowdriftCity_House6_MapScripts::
	.byte 0


SnowdriftCity_House6_EventScript_DojoOldMan::
# 4 "data/maps/SnowdriftCity_House6/scripts.pory"
	msgbox SnowdriftCity_House6_EventScript_DojoOldMan_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House6_EventScript_DojoOldWoman::
# 9 "data/maps/SnowdriftCity_House6/scripts.pory"
	msgbox SnowdriftCity_House6_EventScript_DojoOldWoman_Text_0, MSGBOX_NPC
	end


SnowdriftCity_House6_EventScript_DojoOldMan_Text_0:
# 4 "data/maps/SnowdriftCity_House6/scripts.pory"
	.string "This is a great place to retire.$"

SnowdriftCity_House6_EventScript_DojoOldWoman_Text_0:
# 9 "data/maps/SnowdriftCity_House6/scripts.pory"
	.string "We moved here from BALDESIA.$"
