RatCave_Central_MapScripts::
	.byte 0


RatCave_Central_EventScript_Camper::
# 4 "data/maps/RatCave_Central/scripts.pory"
	msgbox RatCave_Central_Text_Camper, MSGBOX_NPC
	end


RatCave_Central_Text_Camper::
# 8 "data/maps/RatCave_Central/scripts.pory"
	.string "This cave system looks like it was recently\n excavated…\p But whoever made it did a fantastic\n job at constructing it.\p They must be a genius.$"
